title: Michele Riva
logo: /assets/img/logo.png
show_downloads: false
description: "Personal webpage"
lang: en
url: "https://micheleriva24.github.io/micheleriva.github.io/"

plugins:
  - jekyll-seo-tag
  
# Biographic information
name             : "Michele Riva"
pronouns         : "he/him"  
bio              : "PhD student at University of Manchester"
location         : "Office 2.210 <br>8 Upper Brook St <br>M13 9SR Manchester"
employer         : "University of Manchester"
uri              : # URL
email            : "michele.riva@manchester.ac.uk" 
